### ISSUE TITLE
Awkward map layout edge case

### ISSUE THREAD

**Issue by maackle** [lightningrodlabs/acorn#264] opened 2023-03-22 18:02 UTC
Not sure if it's supposed to be guaranteed that cards never overlap arrows, but here is a awkward case where that happens.

![image](https://user-images.githubusercontent.com/896230/226996521-e16bbd15-78f3-427c-9f53-12c0def61571.png)

**Comment by TechSupport26** [comment] 2023-03-23 08:36
I believe this is a duplicate of issue #211

**Comment by Connoropolous** [comment] 2023-04-21 23:36
we are working on a release containing major impacts on the layout, based on the 'multiple parents' feature. I don't think 'no lines crossing cards is something that can be done, but an idea was shared to reduce the overall level of visual featuring of most of the connections. Up for discussion!

**Comment by kbonnici** [comment] 2023-04-24 16:34
Yeah, due to the change in how we are determining coordinates for outcomes (specifically, changing from a tree structure to a graph structure), we can no longer guarantee that those lines will not intersect at any points. The new library we are using does come with multiple algorithms to determine the coordinates, however. It is possible that we could expose these algorithms to the user as options for determining the map layout, and that certain algorithms might aim to reduce line crossings (but still not always be able to reduce them to 0).

**Comment by pegahvaezi** [comment] 2023-10-12 22:53
@Connoropolous did we fix this?

**Comment by Connoropolous** [comment] 2023-10-31 18:37
there are multiple layout options now, so I assume that with those options one can find a satisfying layout

**Closed by Connoropolous** 2023-10-31 18:37 UTC
Labels: ux

**Comment by pegahvaezi** [comment] 2023-10-31 18:40
<img width="306" alt="acorn-map-viewing-options-layout-algorithm" src="https://github.com/lightningrodlabs/acorn/assets/53795528/8584bc4b-22b6-4178-b04d-de3b390d8650">
