### ISSUE TITLE
v1.0.1-alpha : Sharing a project with yourself stops projects from loading.

### ISSUE THREAD

**Issue by TechSupport26** [lightningrodlabs/acorn#125] opened 2022-05-29 08:14 UTC
I have shared an Acorn project with myself and all the projects have stopped showing up and instead are just loading.

![image](https://user-images.githubusercontent.com/65631811/170858166-d595674d-c510-4536-90cf-ec91b7f3669a.png)

Windows 10
Acorn version 1.0.1
Create a project in Acorn. Copy the 5 word secret. Paste the 5 word secret into Join a Project. This will stop projects from loading. (See image above)
I have uninstalled and reinstalled Acorn and have restarted my computer and have not been able to fix it. so if someone finds a way to fix this please leave a comment on how you did it.

**Comment by Connoropolous** [comment] 2022-05-29 18:23
Hi @TechSupport26 
We have seen the same. We believe it is an issue with the gossip of Holochain for the slightly older holochain version Acorn is still running. 

Question: is the data you had so far significant and you would like it not to be lost? I believe, but am not certain, that we can assist with that, if so.

**Comment by TechSupport26** [comment] 2022-05-29 22:36
The data is not important as I have not done any work on any of the Acorn projects yet. I have just removed the databases-2 folder and am starting afresh.

I am having issues with syncing projects from Windows to Linux and vice versa. Two projects went across (From Windows) but the last project just stayed syncing. On the windows Acorn I could see that the other user comes up after they have joined the project but on the Linux side, the user could not see the project.

While I now have two projects coming across from the Linux version it is taking up as much CPU as it can get.

We are going to reset both versions and see if we can share the projects again.

**Comment by TechSupport26** [comment] 2022-05-30 22:49
I was wondering if there is a way to open Acorn in a maximised window instead of a normal window.
I have tried to change how the shortcut opens Acorn but that changes the loading screen and not the window with all the projects.
![image](https://user-images.githubusercontent.com/65631811/171065631-f2a74ea9-cbd4-4238-9132-52c5545afa8c.png)

**Comment by Connoropolous** [comment] 2022-05-31 23:17
Thanks so much for sharing your reports. We have seen almost identical behaviours, and are currently tracking down the cause!

**Comment by Connoropolous** [comment] 2022-05-31 23:18
"I was wondering if there is a way to open Acorn in a maximised window instead of a normal window."
Can you maximize it after it's open?

**Comment by TechSupport26** [comment] 2022-05-31 23:34
Yes I can.

**Comment by TechSupport26** [comment] 2022-06-01 22:21
I have found a way to crash Acorn reliably
You select a card, copy and paste, try and create a child card and boom.
Only one card has to be selected but you can have multiple cards selected
You can click on either of the 2 connection-connector-blue-dot (the blue doth above and below a card)

https://user-images.githubusercontent.com/65631811/171510831-d0e3efd5-ea52-406e-8763-429639ca540d.mp4

Cannot read property 'x' of undefined

TypeError: Cannot read property 'x' of undefined
    at df (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:351:397271)
    at Qa (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:57951)
    at ws (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:104333)
    at xc (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:96859)
    at _c (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:96784)
    at fc (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:93807)
    at file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:45339
    at t.unstable_runWithPriority (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:317:3844)
    at Ko (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:45048)
    at Xo (file:///C:/Users/zephd/AppData/Local/Programs/acorn/resources/app.asar/web/app.js:309:45284)

**Comment by TechSupport26** [comment] 2022-06-03 23:42
No worries.
I am still wondering if there is a way to have acorn open in fullscreen if I were to run it and then close acorn I would move my mouse to the top right corner to click the X and if I have another window open I will accidentally close that instead because the window does not get to the corner.

**Comment by pegahvaezi** [comment] 2022-06-08 01:42
The original issue is resolved in release v1.0.2-alpha.

**Closed by pegahvaezi** 2022-06-08 01:42 UTC
