### ISSUE TITLE
Copy & Paste Tree sections

### ISSUE THREAD

**Issue by zippy** [lightningrodlabs/acorn#258] opened 2023-03-15 13:17 UTC
In working on trees I want to be able to copy a tree or branch a tree and paste it into a different tree.

**Comment by Connoropolous** [comment] 2023-08-10 01:19
duplicate of #128 but I'll close that one

**Comment by Connoropolous** [comment] 2023-08-10 01:22
There is also #210 with more detailed thinking

**Comment by Connoropolous** [comment] 2023-10-30 18:59
let's keep #210

**Closed by Connoropolous** 2023-10-30 18:59 UTC
